language: ruby
rvm:
- 2.5.1
dist: trusty
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=922 http://localhost &
- cd MySNiPs
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- bundle exec rake db:create
- bundle exec rake db:schema:load
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: LQBOEbLFVBQSrEsIGFMlJqeu9Zc0M4UvgfW5Bu0Y5muvPmghmpyCcZz8TMTPxQad+v4afDCHizQlMElaRSsdkCvJzCM97G8wwodjI1hvP14hsh7oYPDC3tnk0Fg+EtAtKtgmar7HHCKHE1oqaVMr4k6HzIUw0lEb6t2xZSyEDFunBvxsM4lJscbksG6c5CCdlAeWuSK4yB5zXPJPo4eaC7XzaKjA1gidryJ9mtw21Zuuj/HdetEiDXUVP0Ig+Ggdo1Pn+yzKL9ppH78WuxMd5xbIF7qHJBaL01DtyXsA+4/BUD/5q/cabMw/gQW6g7lCXMgUFOALtCJGNUbLDSToy/sQUE/k2FzWlMTk0kwCxYG0D30XHOKOfs1HqVXs1feZ5TEpuxSdkZZS0rT9fRuyujjcMrdkhNqzJ45bbjtog3s/9WaQGBaCKSwi8A2ybXl5ZyyGyo8ITwCCahs5STR+uUbsHKVThVlRrCdcaWj6NN9SZfgm8C5RqQC8vIw9RznD9vlpgVnZReN/hoGqMGq5sUnf0Y9UPz35/bPLula88fmuVaIDbPFLd5A6SAmNlocKpynuO+nWtyjT8KAh81OurGt8l23eZ7oDLrE/7rToMYyiPOftFQuzXYtMhdsDA3PvHl6206TKUzakribRIPDULUg7uz4BGoMZHPzmXUBB4k0=
  app: mysnips
  on:
    repo: ricardoebbers/MySNiPs
    branch: master
